#!/usr/bin/env python3
"""Generate a 24-bit packed mono LUT for a 1.5 kHz pure tone at 48 kHz.

48000 Hz / 1500 Hz = 32 samples per cycle exactly, so a 32-entry LUT
contains one full cycle and can be looped indefinitely with phase
accumulation modulo 32.

Output is a C header with the samples stored as 32 * 3 = 96 bytes
(little-endian 24-bit signed). The runtime packet builder duplicates
each mono sample to L/R for stereo output.

Run: python3 tools/gen_test_tone_lut.py > main/test_tone_lut.h
"""

import math
import sys

SAMPLES_PER_CYCLE = 32  # 48000 / 1500
PEAK = (1 << 23) - 1    # signed 24-bit full scale = 8388607


def main():
    out = sys.stdout
    out.write("// Auto-generated by tools/gen_test_tone_lut.py — do not edit.\n")
    out.write("// 32 samples of a 1.5 kHz sine at 48 kHz, signed 24-bit\n")
    out.write("// little-endian packed (3 bytes per sample, mono).\n")
    out.write("//\n")
    out.write(f"// PEAK = {PEAK}  (full-scale signed 24-bit)\n")
    out.write("#pragma once\n\n")
    out.write("#include <stdint.h>\n\n")
    out.write("#define TEST_TONE_LUT_SAMPLES 32\n")
    out.write("#define TEST_TONE_LUT_BYTES_PER_SAMPLE 3\n\n")
    out.write("static const uint8_t k_test_tone_lut_24bit[TEST_TONE_LUT_SAMPLES * 3] = {\n")
    for i in range(SAMPLES_PER_CYCLE):
        phase = 2.0 * math.pi * i / SAMPLES_PER_CYCLE
        v = int(round(PEAK * math.sin(phase)))
        if v < 0:
            v += (1 << 24)  # two's complement 24-bit
        b0 = v & 0xFF
        b1 = (v >> 8) & 0xFF
        b2 = (v >> 16) & 0xFF
        out.write(f"    0x{b0:02X}, 0x{b1:02X}, 0x{b2:02X},  // sample {i:2d}\n")
    out.write("};\n")


if __name__ == "__main__":
    main()
