// test_golden_rx.cpp
// ──────────────────────────────────────────────────────────────────────────────
// Golden RX test: reads pre-generated WAV files from tests/tx_e2e/golden/ and
// decodes them with the ft8_lib reference decoder, asserting that each file
// produces the exact expected message.
//
// This test validates the decoder independently of the encoder: the WAV files
// are committed artifacts, so the test will catch decoder regressions even if
// the encoder is never run.
//
// Golden WAVs are generated by running gen_golden (see CMakeLists.txt).
// Regenerate them whenever the encoder, synth, or sample rate intentionally changes:
//   cd build && ./Release/gen_golden.exe ../golden   (Windows)
//   cd build && ./gen_golden ../golden               (Linux/macOS)
// Then commit the updated WAV files.
// ──────────────────────────────────────────────────────────────────────────────

#include <cstdio>
#include <cstring>
#include <vector>
#include "decode_helper.h"
#include "../../components/ft8_lib/ft8/constants.h"

// GOLDEN_DIR is injected by CMake as an absolute path so ctest can find the
// files regardless of where the test binary is run from.
#ifndef GOLDEN_DIR
#define GOLDEN_DIR "golden"
#endif

struct GoldenCase {
    const char*    filename;
    const char*    expected;    // exact normalized text the decoder must return
    ftx_protocol_t proto;
    bool           known_fail;  // if true, failure is reported but does not fail the test
};

// This table must stay in sync with gen_golden.cpp.
static const GoldenCase CASES[] = {
    { "ft8_w1abc_k9xyz_rr73.wav",  "W1ABC K9XYZ RR73", FTX_PROTOCOL_FT8, false },
    { "ft8_cq_w1xyz_fn42.wav",     "CQ W1XYZ FN42",    FTX_PROTOCOL_FT8, false },
    { "ft8_w1abc_k9xyz_neg12.wav", "W1ABC K9XYZ -12",  FTX_PROTOCOL_FT8, false },
    { "ft8_w1abc_k9xyz_fn42.wav",  "W1ABC K9XYZ FN42", FTX_PROTOCOL_FT8, false },
    { "ft4_w1abc_k9xyz_rr73.wav",  "W1ABC K9XYZ RR73", FTX_PROTOCOL_FT4, false },
    { "ft4_cq_w1xyz_fn42.wav",     "CQ W1XYZ FN42",    FTX_PROTOCOL_FT4, false },
    { "ft4_w1abc_k9xyz_neg12.wav", "W1ABC K9XYZ -12",  FTX_PROTOCOL_FT4, false },
};
static const int N_CASES = (int)(sizeof(CASES) / sizeof(CASES[0]));

int main()
{
    printf("Golden RX Test\n");
    printf("======================================\n\n");

    int passed = 0, failed = 0;

    for (int i = 0; i < N_CASES; i++) {
        const GoldenCase& c = CASES[i];
        printf("[%d/%d] %s: ", i + 1, N_CASES, c.filename);
        fflush(stdout);

        // ── Load WAV ──────────────────────────────────────────────────────
        char path[512];
        snprintf(path, sizeof(path), "%s/%s", GOLDEN_DIR, c.filename);

        std::vector<float> pcm;
        int fs = 0;
        if (read_wav(path, pcm, &fs) != 0) {
            // read_wav already printed the error
            printf("FAIL (cannot read WAV: %s)\n", path);
            failed++;
            continue;
        }

        // ── Decode ────────────────────────────────────────────────────────
        decode_clear_hashes();
        DecodeResult res = decode_pcm(pcm.data(), (int)pcm.size(), fs, c.proto);

        if (!res.found) {
            if (c.known_fail) {
                printf("KNOWN-FAIL (no decode — pre-fix device recording; re-record after flashing)\n");
            } else {
                printf("FAIL (no decode)\n");
                failed++;
            }
            continue;
        }

        // ── Compare ───────────────────────────────────────────────────────
        char norm_expected[256];
        normalize_text(c.expected, norm_expected, sizeof(norm_expected));

        if (strcmp(norm_expected, res.text) == 0) {
            printf("PASS (SNR=%.1f)\n", res.snr);
            passed++;
        } else if (c.known_fail) {
            printf("KNOWN-FAIL (expected='%s', got='%s')\n", norm_expected, res.text);
        } else {
            printf("FAIL (expected='%s', got='%s')\n", norm_expected, res.text);
            failed++;
        }
    }

    printf("\n======================================\n");
    printf("Results: %d/%d passed\n", passed, N_CASES);
    return (failed > 0) ? 1 : 0;
}
